#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun  9 19:58:02 2018

@author: chenchacha
"""

import pickle 
import matplotlib.pyplot as plt

pkl_file = open('./data/data_train_reducedn.pkl', 'rb')

data_test = pickle.load(pkl_file)
#pprint.pprint(data1)

pkl_file.close()

fig, axes = plt.subplots(10, 10, figsize=(10, 10))
for i in range(10):
    for j in range(10):
        index=i*10+j
        axes[i][j].imshow(data_test[100], interpolation='none')
        axes[i][j].set_xticks([])
        axes[i][j].set_yticks([])
        
